DECLARE
V_COUNT INTEGER;
BEGIN
SELECT COUNT(TABLE_NAME) INTO V_COUNT from USER_TABLES where TABLE_NAME = '__EFMigrationsHistory';
IF V_COUNT = 0 THEN
Begin
BEGIN 
EXECUTE IMMEDIATE 'CREATE TABLE 
"__EFMigrationsHistory" (
    "MigrationId" NVARCHAR2(150) NOT NULL,
    "ProductVersion" NVARCHAR2(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
)';
END;

End;

END IF;
EXCEPTION
WHEN OTHERS THEN
    IF(SQLCODE != -942)THEN
        RAISE;
    END IF;
END;
/

DECLARE
    USEREXIST INTEGER;
    USER_NOT_EXIST EXCEPTION;
    PRAGMA EXCEPTION_INIT( USER_NOT_EXIST, -01435 );
BEGIN
SELECT COUNT(*) INTO USEREXIST FROM ALL_USERS WHERE USERNAME='HRCMS';
IF (USEREXIST = 0) THEN
    RAISE USER_NOT_EXIST;
END IF;
END;
/

BEGIN 
EXECUTE IMMEDIATE 'CREATE TABLE 
"HRCMS"."CONTACT" (
    "Id" RAW(16) NOT NULL,
    "FIRST_NAME" VARCHAR2(4000) NOT NULL,
    "LAST_NAME" VARCHAR2(4000) NOT NULL,
    CONSTRAINT "PK_CONTACT" PRIMARY KEY ("Id")
)';
END;
/

COMMENT ON COLUMN "HRCMS"."CONTACT"."FIRST_NAME" is N'This is a comment for the FirstName column'
/

COMMENT ON COLUMN "HRCMS"."CONTACT"."LAST_NAME" is N'This is a comment for the LastName column'
/

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES (N'20231127181603_InitialMigration', N'7.0.14')
/

